feed/urls.py
from django.urls import path

from . import views


app_name = "feed"

urlpatterns = [
    path("", views.HomePage.as_view(), name="index"),
    path("<int:pk>/", views.PostDetailView.as_view(), name='detail'),
    path("new/", views.CreateNewPost.as_view(), name='new_post'),
]

profiles/urls.py
from django.urls import path


from . import views

app_name = "profiles"


urlpatterns = [
    path("<str:username>/", views.ProfileDetailView.as_view(), name="detail"),
]

til/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from feed import urls as feed_urls
from django.conf import settings
from django.conf.urls.static import static
from profiles import urls as profiles_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(feed_urls, namespace="feed")),
    path("profile/", include(profiles_urls, namespace="profiles")),
    path("", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feed/models.py
from django.contrib.auth.models import User
from django.db import models



class Post(models.Model):
    text = models.CharField(max_length=240)
    date = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(
        User, 
        on_delete=models.CASCADE,
        
    )
    
    def __str__(self):
        return self.text[0:100]

profiles/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from sorl.thumbnail import ImageField

class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        # related_name="profile"
    )
    image = ImageField(upload_to='profiles')
    
    def __str__(self):
        return self.user.username
    
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    """Create a new Profile() object when a Django user is created"""
    if created:
        Profile.objects.create(user=instance)

feed/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Post

class HomePage(ListView):
    http_method_names = ["get"]
    template_name = "feed/homepage.html"
    model = Post
    context_object_name = "posts"
    queryset = Post.objects.all().order_by('-id')[0:30]
    

class PostDetailView(DetailView):
    http_method_names=["get"]
    model = Post
    template_name = "feed/detail.html"
    context_object_name = "post"
    
class CreateNewPost(LoginRequiredMixin, CreateView):
    model = Post
    template_name = "feed/create.html"
    fields = ['text']
    success_url = "/"
    
    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)
    
    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user
        obj.save()
        return super().form_valid(form)

profiles/views.py
from django.contrib.auth.models import User
from django.views.generic import DetailView

class ProfileDetailView(DetailView):
    http_method_names = ["get"]
    template_name = "profiles/detail.html"
    model = User
    context_object_name = "user"
    slug_field = "username"
    slug_url_kwarg = "username"

feed/templates/feed/create.html
{% extends 'base.html' %} 

{% block title %} Create a new post {% endblock title %}


{% block body %}
        <div class="p-16">
            <form method="POST" action=".">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="bg-transparent hover:bg-gray-800 text-gray-700 font-semibold hover:text-white py-2 px-4 border border-gray-800 hover:border-transparent rounded text-right" type="submit">
                    Post
                </button>
            </form>
        </div>
{% endblock body %}

feed/templates/feed/detail.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
    {{ post.text }} by {{ post.author.username }}
{% endblock title %}
    

{% block body %}
{% include 'includes/post.html' %}
{% endblock body %}
    

feed/templates/feed/homepage.html
{% extends 'base.html' %}

{% block title %}
    Home page
{% endblock title %}



{% block body %}
    {%for post in posts%}
      {% include 'includes/post.html' with post=post show_detail_link=True %}
    {%endfor%}
{% endblock body %}
    

til/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} Default {% endblock title %}</title>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body>
    <!-- component -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/material-design-icons/3.0.1/iconfont/material-icons.min.css"
      integrity="sha256-x8PYmLKD83R9T/sYmJn1j3is/chhJdySyhet/JuHnfY="
      crossorigin="anonymous"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;500;700;900&display=swap"
      rel="stylesheet"
    />
    <style>
      html,
      body {
        font-family: "Rubik", sans-serif;
      }

      /* navigation 
 - show navigation always on the large screen devices with (min-width:1024)
*/

      @media (min-width: 1024px) {
        .top-navbar {
          display: inline-flex !important;
        }
      }
    </style>
    <!-- Navbar -->
    <nav class="flex items-center bg-gray-800 p-3 flex-wrap">
      <a href="/" class="p-2 mr-4 inline-flex items-center">
        <span class="text-xl text-white font-bold uppercase tracking-wide"
          >Django v3</span
        >
      </a>
      <button
        class="text-white inline-flex p-3 hover:bg-gray-900 rounded lg:hidden ml-auto hover:text-white outline-none nav-toggler"
        data-target="#navigation"
      >
        <i class="material-icons">menu</i>
      </button>
      <div
        class="hidden top-navbar w-full lg:inline-flex lg:flex-grow lg:w-auto"
        id="navigation"
      >
        <div
          class="lg:inline-flex lg:flex-row lg:ml-auto lg:w-auto w-full lg:items-center items-start flex flex-col lg:h-auto"
        >
          <a
            href="/"
            class="lg:inline-flex lg:w-auto w-full px-3 py-2 rounded text-gray-400 items-center justify-center hover:bg-gray-900 hover:text-white"
          >
            <span>Main</span>
          </a>
          {% if request.user.is_authenticated %}
          <li>

            <a
            href="#"
            class="lg:inline-flex lg:w-auto w-full px-3 py-2 rounded text-gray-400 items-center justify-center hover:bg-gray-900 hover:text-white show-modal"
            >
            <span>Create new post</span>
          </a>
        </li>
        <li>
          <a
          href="{% url 'account_logout' %}"
          class="lg:inline-flex lg:w-auto w-full px-3 py-2 rounded text-gray-400 items-center justify-center hover:bg-gray-900 hover:text-white"
          >
          <span>Logout</span>
        </a>
        </li>
          {% else %}
          <a
            href="{% url 'account_login' %}"
            class="lg:inline-flex lg:w-auto w-full px-3 py-2 rounded text-gray-400 items-center justify-center hover:bg-gray-900 hover:text-white"
          >
            <span>Login</span>
          </a>
          {% endif %}
        </div>


        
      </div>
    </nav>
<!-- Modal -->
<!-- component -->

{% if request.user.is_authenticated %}
  <div class="modal h-screen w-full fixed left-0 top-0 flex justify-center items-center bg-black bg-opacity-50 hidden">
    <!-- modal -->
    <div class="bg-white shadow-lg w-10/12 md:w-1/3 rounded-md">
      <!-- modal header -->
      <div class="border-b px-4 py-2 flex justify-between items-center rounded-t-md bg-gray-700">
        <h3 class="font-semibold text-lg text-white">Create New Post</h3>
      </div>
      <!-- modal body -->
      <div class="p-3">
          <textarea class="border-2 border-grey-700 my-4 js-post-text w-full" Placeholder="Enter your post" maxlength="240" rows="3"></textarea>
      </div>
      <div class="flex justify-end items-center w-100 border-t p-3">
        <button class="bg-gray-700 hover:bg-gray-900 px-3 py-1 rounded mr-1.5 text-white js-submit">Post</button>
        <button class="bg-red-700 hover:bg-red-900 px-3 py-1 rounded text-white close-modal">Cancel</button>
      </div>
    </div>
  </div>
  <!-- TODO: Modify JS to submit post via modal. -->
  <script>
    const modal = document.querySelector('.modal');

    const showModal = document.querySelector('.show-modal');
    const closeModal = document.querySelectorAll('.close-modal');

    showModal.addEventListener('click', function (){
      modal.classList.remove('hidden')
    });

    closeModal.forEach(close => {
      close.addEventListener('click', function (){
        modal.classList.add('hidden')
      });

      postModal.addEventListener('click', function (){
        console.log("Submitted?")
      })
    });
  </script>
<!-- Modal End -->
{% endif %}


<script src="{% static 'js/main.js' %}"></script>
  
    <script>
      $(document).ready(function () {
        $(".nav-toggler").each(function (_, navToggler) {
          var target = $(navToggler).data("target");
          $(navToggler).on("click", function () {
            $(target).animate({
              height: "toggle",
            });
          });
        });
      });
    </script>
    <!-- End navbar -->
    <!-- Body -->

      {% block body %} Default base file {% endblock body %}
      
    <!-- End body -->
  </body>
</html>

til/templates/includes/post.html
{% load thumbnail %}

<!-- post component -->
        <div class='flex items-center justify-center p-3'>  
            <div class="rounded-xl border p-5 shadow-md w-9/12 bg-white">
            <div class="flex w-full items-center justify-between border-b pb-3">
              <div class="flex items-center space-x-3">
                <a href="{% url 'profiles:detail' post.author.username %}" class="flex items-center">

                  {% thumbnail post.author.profile.image "372x372" crop="center" as im %}
                  <img class='h-8 w-8 rounded-full bg-slate-400' src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="avatar">
                  {% endthumbnail %}
                  <div class="text-lg font-bold text-slate-700">{{ post.author.username }}</div>
                </a>
                </div>
                <div class="flex items-center space-x-8">
                  <button class="rounded-2xl border bg-neutral-100 px-3 py-1 text-xs font-semibold">Category</button>
                  <div class="text-xs text-neutral-500">{{ post.date }}</div>
              </div>
            </div>
        
            <div class="mt-4 mb-6">
              <div class="mb-3 text-xl font-bold">{{ post.text }}</div>
            {% if show_detail_link %}
                <a class="text-sm text-neutral-600" href="{% url 'feed:detail' post.id %}">Read more</div> 
            {% else %}
                <a class="text-sm text-neutral-600" href="{% url 'feed:index' %}">Go back</div> 
            {% endif %}
            </div>
          </div>
        </div>